//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArduinoProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Table
    {
        public int Id { get; set; }
        public string Kullanici_Id { get; set; }
        public string Kullanici_Sifre { get; set; }
        public Nullable<int> Kullanici_Telefon { get; set; }
        public string Kullanici_Mail { get; set; }
    }
}
